# Generated by Django 5.0.1 on 2024-11-18 14:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='total_solar_potential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BuildingFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('orientation', models.FloatField()),
                ('tilt', models.FloatField(default=90)),
                ('solar_potential', models.FloatField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='city_3D.building')),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('solar_potential', models.FloatField(default=0.0)),
                ('is_in_shadow', models.BooleanField(default=False)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='city_3D.buildingface')),
            ],
        ),
    ]
