# Generated by Django 5.0.1 on 2024-11-20 15:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0002_building_total_solar_potential_buildingface_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=32643),
        ),
    ]
