# Generated by Django 5.0.1 on 2024-11-21 13:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0003_alter_building_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingface',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=32643),
        ),
        migrations.AlterField(
            model_name='grid',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=32643),
        ),
    ]
