# Generated by Django 5.0.1 on 2024-11-21 14:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0004_alter_buildingface_geometry_alter_grid_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingface',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(dim=3, srid=32643),
        ),
        migrations.AlterField(
            model_name='grid',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(dim=3, srid=32643),
        ),
    ]
