# Generated by Django 5.0.1 on 2024-11-27 13:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0005_alter_buildingface_geometry_alter_grid_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=32643)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('height_start', models.FloatField(blank=True, null=True)),
                ('height_end', models.FloatField(blank=True, null=True)),
                ('solar_potential', models.FloatField(default=0.0)),
                ('is_in_shadow', models.BooleanField(default=False)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids_2d', to='city_3D.buildingface')),
            ],
        ),
    ]
