# Generated by Django 5.0.1 on 2024-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0006_grid2d'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid2d',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
