# Generated by Django 5.0.1 on 2024-11-28 09:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0007_grid2d_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(dim=3, srid=32643)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('z_position', models.IntegerField()),
                ('solar_potential', models.FloatField(default=0.0)),
                ('is_in_shadow', models.BooleanField(default=False)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids_3d', to='city_3D.buildingface')),
            ],
        ),
    ]
