# Generated by Django 5.0.1 on 2024-11-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0008_grid3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid3d',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
