# Generated by Django 5.0.1 on 2024-11-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0009_grid3d_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
