# Generated by Django 5.0.1 on 2024-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0010_grid_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingface',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
