# Generated by Django 5.0.1 on 2024-11-30 09:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0011_buildingface_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualGridCentroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(dim=3, srid=32643)),
                ('building_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centroids', to='city_3D.buildingface')),
            ],
        ),
    ]
