# Generated by Django 5.0.1 on 2024-12-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0012_virtualgridcentroid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('shadow', models.BooleanField()),
                ('centroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_analysis', to='city_3D.virtualgridcentroid')),
            ],
            options={
                'unique_together': {('centroid', 'month', 'hour')},
            },
        ),
    ]
