# Generated by Django 5.0.1 on 2024-12-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_3D', '0013_shadowanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potential_Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('date', models.DateField()),
                ('potential', models.FloatField(blank=True, null=True)),
                ('irradiance', models.FloatField(blank=True, null=True)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential', to='city_3D.buildingface')),
            ],
        ),
    ]
